language: node_js
node_js:
- '6'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/doc.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "HmvMNCSVBjvPsc5fn8TZ2II2zd8fnGOOwA4nj2iMQJQJngtNgFnQ/kF6/rinnGXh5qi0aboXRCBYNwz0OU4oG3fFkzttwTakZCbJLHoH4brk1xmX9UCdY81wVUndZu1kspYNNe/e18UZXpaix+jKzF1NZtlsiCdV/RSHnq3uhoZ4PjZknNf67NM0joZNqg/XjoAqsvX7LbvI7wGVqsHohVqY08Rp2I5WSG8/9Cb/FoP4UFPAcMn7AdFNymiBhwED9FDS41nA1/Rhm21IvedijlEWu6ld3naPnQYubVbT9ttJTjeyHvNcu71cZGyzkzM0DjUy1Vr+n0gsQXe8t3qZ7d4BM7cTtGksTxpa8z1dfgg0fre3/mRbeV5JMgUrwMd4lxNrWCUNZ+DwBykeZdVvsX0FsSoSbmGDj9Ccn2NqaIhsoJXJzfRmMc1HgOqJKMg1/sx2o6yoLrDDabtoiXd8p3in11NPNKBa3zlqKEqgSqDKdPhKYhOb2rgOnnuHcH8YPfOanT6h0CChQEdOz9+7IOW/YfcaPgnxisDgZ+faTb2kOlGfz+0kCAno7lFscf9lOWTbXk7NNCWm6ZW9IrI+q0OYKoxpsJAFoB+2pzLN+SEjMLQU/OrpYnEikKV6M3iDdSRX4mIieX/RU/BiDPY3eYClUr9aE0lBlPPbNbLmyDs="
env:
  secure: "2W/kuOo0rFbVS4n+bTtpKtCozohQ+amqM877PijW+kEHVGnmSBtjv0La6FC9rawjpuDjFVKNACKzWpSegqyuBOSmfIsepFm2MOovrI2nQ175J5VEIoeVM4t2OtMIqUbV2USHzKi1l2gRuevFsU0RX9cLDgxEQR5SRKFKdzQ9+fqg+XwIwZB8z1Fv1VxLM2UP8Ngngd6L4bUo8WA8YwFXDjy7j0kQisvjql6YIn4Bj6gBOK5W7ef5emFg8bJ/i/bGiIs6EsyZOm0uuYJ7V+jwzm9l1MVOyjVNjedpHwSfdubX5KJk0/DgPOwRu6mM4BoPZyW5VHoTvneHaR64nknM7yxK9DNfPmQH7cAu4mVn83bg0IjIZ5FiTj+XAzLq5ZWoGFf4mWtrcmJbHHrzUyd24bI7foXXHrsuaUlSBAt4vgWSX4/u//IOGP2glV2JMfTm2Gu3TyoYZ0w/Yti0jEu06klLYw1TqOyIXXjRZMuc+jm3ss2xj9fZqfAD3rLk30kxeuBXsd7NCKnXi8Wx0PgmevHGHTDZDTGM0cFqvYhrp3/JkTp5GQuaeQlLeDNXwXGqyju8jdbNxVG2D0dxBw7M2MzxynGCDG6boj7ShW/14NMyD+VwhYmgpO96Q0CsAO9me28JoWbI2Pe6qlS8CwfFGTnJQMjusUufvBySIPXn1Fo="
