language: node_js
node_js:
- '10'
before_install:
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
- npm install jsdoc publish-if-needed npm@latest -g
install:
- npm install jsdoc -g
- npm install
script:
- "./ci/build.js"
- "./ci/shim.js"
- "./ci/test.js"
after_success:
- publish-if-needed
env:
  global:
  - secure: o9SWp91RrzYAaS6tXYV4jjvS15kIsEQ0HmpaE8bo8Uz2iez4I3p/2NHzjs58iDsBapnjfSWzh1gkBydIi2BDXf5w5I9SlvDjZegUAwpdUHjbcZU77shYQTODqFdy8i4WBAbpNmwwsPx0FYXlb3sPNtBnKG+p6rOhNdUXQnY/HIKHrumDw1tWcLRHmKPku/pW+VHTdm8ErOqu+aIZ33wYV4JwWTVH7nDuTo5L3YcvnpZ0ivVGVHomO4vUmXrDy7z4ZcBoWIt0vWGiOo3tiapnO1+uwASM9UClwWApbhkXHIwtoXjsR73RONoFp6x8WA3wPGkvpeQEBF3+MhFUQ/M6zI0PQMQHWDqx81M1LIRFfeayf8OjxbytQDkTHrUCv7hXZPYaoBOjGecr0inFZJ6Tf/N7ESckeCQMyqZgHzGLumXFAvVQTSSvjFbAYuuQX/xGGALbzy0Ep0NyX9QJbHez7bgULePlx8qGNt7J5JXxtBau1YJGgcHjssNdc8No0q7MkaGlvYA0nhrpVRtuNFOJQnt5ob3txJenGAdP6ZiHdgrjCsZRtHo6GJfvW0Vi2zXVwBcjUXVfvak16gT/q8U0S2YZL8jnVm3GYoFpLUS1uD3/BXLML7rpVJ4JZl4YKq9EOGyBcQMVDxsPsRTOhb0RkjXf2OWeQK9u6bBO4PMRnDY=
